-   hosts: mysql
    sudo: yes
    handlers:
        - include: handlers/mysql.yml
    roles:
        - common
        - mysql

-   hosts: mysqlmaster
    sudo: yes
    handlers:
        - include: handlers/mysql.yml
    roles:
        - mysqlmaster
    tags:
        - mysqlmaster
