-   name: Install supporting packages
    apt: pkg={{ item }} state=present
    with_items:
        - libusb-1.0-0-dev

-   name: Install phidgets source
    script: install_phidgets.sh
            creates=/usr/lib/libphidget21.so

-   name: Install phidgets python library
    pip: name='http://www.phidgets.com/downloads/libraries/PhidgetsPython.zip'
    tags:
        - python
