-   name: Install base dev packages
    apt: pkg={{ item }} state=present
    tags: system
    with_items:
        - cpp
        - gcc
        - make
        - unzip
        - zip
        - g++
        - build-essential
        - screen
        - ntp
        - ntpdate
        - vim
        - python-dev
        - python-setuptools

-   name: Install pip
    easy_install: name=pip
    tags: system

-   name: Install virtualenv
    pip: name=virtualenv
    tags:
        - system
        - python

-   name: Install virtualenvwrapper
    pip: name=virtualenvwrapper
    tags:
        - system
        - python
